-- CreateTable
CREATE TABLE "theme_settings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "primaryColor" TEXT NOT NULL DEFAULT '#3b82f6',
    "primaryForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "primaryHoverColor" TEXT NOT NULL DEFAULT '#2563eb',
    "secondaryColor" TEXT NOT NULL DEFAULT '#8b5cf6',
    "secondaryForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "secondaryHoverColor" TEXT NOT NULL DEFAULT '#7c3aed',
    "accentColor" TEXT NOT NULL DEFAULT '#10b981',
    "accentForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "accentHoverColor" TEXT NOT NULL DEFAULT '#059669',
    "backgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "mutedBackgroundColor" TEXT NOT NULL DEFAULT '#f8fafc',
    "cardBackgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "foregroundColor" TEXT NOT NULL DEFAULT '#0f172a',
    "mutedForegroundColor" TEXT NOT NULL DEFAULT '#64748b',
    "borderColor" TEXT NOT NULL DEFAULT '#e2e8f0',
    "popoverBackgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "popoverForegroundColor" TEXT NOT NULL DEFAULT '#0f172a',
    "successColor" TEXT NOT NULL DEFAULT '#10b981',
    "successForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "warningColor" TEXT NOT NULL DEFAULT '#f59e0b',
    "warningForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "errorColor" TEXT NOT NULL DEFAULT '#ef4444',
    "errorForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "infoColor" TEXT NOT NULL DEFAULT '#3b82f6',
    "infoForegroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "heroBadgeBackground" TEXT NOT NULL DEFAULT '#f59e0b',
    "heroBadgeText" TEXT NOT NULL DEFAULT '#ffffff',
    "heroScrollIndicatorColor" TEXT NOT NULL DEFAULT '#ffffff',
    "welcomeBadgeBackground" TEXT NOT NULL DEFAULT '#3b82f6',
    "welcomeBadgeText" TEXT NOT NULL DEFAULT '#ffffff',
    "welcomeFeatureIcon1Color" TEXT NOT NULL DEFAULT '#10b981',
    "welcomeFeatureIcon2Color" TEXT NOT NULL DEFAULT '#3b82f6',
    "welcomeFeatureIcon3Color" TEXT NOT NULL DEFAULT '#f59e0b',
    "productsNewBadgeColor" TEXT NOT NULL DEFAULT '#10b981',
    "productsPopularBadgeColor" TEXT NOT NULL DEFAULT '#f59e0b',
    "productsCategoryBadgeBackground" TEXT NOT NULL DEFAULT '#ffffff',
    "productsCategoryBadgeText" TEXT NOT NULL DEFAULT '#0f172a',
    "testimonialsBadgeBackground" TEXT NOT NULL DEFAULT '#f59e0b',
    "testimonialsBadgeText" TEXT NOT NULL DEFAULT '#ffffff',
    "testimonialsStarColor" TEXT NOT NULL DEFAULT '#f59e0b',
    "testimonialsVerifiedBadgeColor" TEXT NOT NULL DEFAULT '#3b82f6',
    "floatingCTAGlowColor" TEXT NOT NULL DEFAULT '#3b82f6',
    "floatingCTAParticlesColor" TEXT NOT NULL DEFAULT '#ffffff',
    "heroOverlayStartColor" TEXT NOT NULL DEFAULT 'rgba(0,0,0,0.6)',
    "heroOverlayMiddleColor" TEXT NOT NULL DEFAULT 'rgba(0,0,0,0.4)',
    "heroOverlayEndColor" TEXT NOT NULL DEFAULT 'rgba(0,0,0,0.7)',
    "decorativeElement1Color" TEXT NOT NULL DEFAULT 'rgba(59,130,246,0.2)',
    "decorativeElement2Color" TEXT NOT NULL DEFAULT 'rgba(139,92,246,0.2)',
    "decorativeElement3Color" TEXT NOT NULL DEFAULT 'rgba(16,185,129,0.2)',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "theme_settings_pkey" PRIMARY KEY ("id")
);
