version: "3.8"

services:
  app:
    build: .
    container_name: optique_app
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/optique_db
      NODE_ENV: production
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: optique_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optique_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: optique_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/app/uploads:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

volumes:
  pgdata:
